config/routes.rb
Rails.application.routes.draw do
   devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :checklists do
    resources :show, only: [:index]

    resources :items, only: %i[new create update destroy] do
      resource :item_resolutions, only: [:create, :destroy]
    end
  end

  resources :checklist_templates do
    resources :show, only: [:index]
    resources :template_items, only: %i[create update destroy]
    resource :checklist_copy, only: %i[create]
  end

  resources :users do
    resources :checklist_templates, module: 'users', only: %i[index show]
  end

end

app/models/checklist_template.rb
# User Template checklist:
# this template creates checklists with items and
# can be used multiple times to create different checklists with same items
class ChecklistTemplate < ApplicationRecord
  include AASM

  has_many :checklists
  has_many :template_items
  belongs_to :user
  accepts_nested_attributes_for :checklists

  validates :title, presence: true, length: { maximum: 100 }

  acts_as_taggable
  searchkick

  aasm.attribute_name :visibility

  aasm do
    state :everyone, initial: true
    state :owner
    state :one_time

    event :to_public do
      transitions from: %i[owner one_time], to: :everyone
    end

    event :to_private do
      transitions from: %i[everyone one_time], to: :owner
    end

    event :to_one_time do
      transitions from: %i[everyone owner], to: :one_time
    end
  end
end

app/controllers/checklist_templates_controller.rb
class ChecklistTemplatesController < ApplicationController
  before_action :checklist_template, only: %i[show]
  before_action only: %i[new create] do
    authorize_role(:checklist_template)
  end

  def index
    @checklist_templates = ChecklistTemplate.everyone.paginate(page: params[:page])

    keyword = params[:search]
    @checklist_templates = @checklist_templates.search(keyword) if keyword.present?
  end

  def new
    @checklist_template = ChecklistTemplate.new.decorate
  end

  def create
    @checklist_template = current_user.checklist_templates.build(checklist_template_params).decorate
    if @checklist_template.save
      redirect_to checklist_template_path(@checklist_template), notice: t('checklist_template.success_create')
    else
      render :new, alert: t('checklist_template.fail_create')
    end
  end

  def show
    @template_items = @checklist_template.template_items
    @template_item = TemplateItem.new(checklist_template: @checklist_template)
  end

  private

  def checklist_template
    @checklist_template ||= ChecklistTemplate.find(params[:id]).decorate
    authorize @checklist_template
  end

  def checklist_template_params
    params.require(:checklist_template).permit(:title, :tag_list, :visibility)
  end
end

app/controllers/users/checklist_templates_controller.rb
class Users::ChecklistTemplatesController < ApplicationController
  def index
    @checklist_templates = user.checklist_templates
  end

  private

  def user
    @user ||= User.find(params[:user_id])
  end
end

app/views/checklist_templates/_new_template_item_modal.html.haml
%a{ href: "#", "data-toggle" => "modal", "data-target" => "#new_template_item" } New template item

.modal.fade{ id: "new_template_item", tabindex: "-1",
    role: "dialog", "aria-labelledby" => "exampleModalLabel", "aria-hidden" => "true" }
  .modal-dialog{ role: "document" }
    .modal-content
      .modal-header
        %h5.modal-title= t('views.template_items.create.title')
        %button.close{ type: "button", "data-dismiss" => "modal", "aria-label" => "Close" }
          %span{ "aria-hidden" => "true" } &times;
      .modal-body
        = simple_form_for [checklist_template, template_item] do |f|
          = f.input :title
          = f.button :submit
      .modal-footer
        %button.btn.btn-secondary{ type: "button", "data-dismiss" => "modal" }= t('button.close')

app/views/checklist_templates/index.html.haml
.container
  %h1= t('views.checklist_templates.index.search')
  %ul
  - if @checklist_templates.any?
    - @checklist_templates.each do |template|
      %li= link_to template.title, checklist_template_path(template)
  - else
    %p Results not found

  = will_paginate @checklist_templates, renderer: WillPaginate::ActionView::BootstrapLinkRenderer
  = link_to t('views.checklist_templates.create.title'), new_checklist_template_path

app/views/checklist_templates/new.html.haml
.container
  = simple_form_for @checklist_template do |f|
    = f.input :title
    = f.input :visibility
    = f.input :tag_list, input_html: { class: 'tag_list', value: @checklist_template.show_tags }
    = f.submit

app/views/checklist_templates/show.html.haml
.container
  %h1= t('views.checklist_templates.show.title')
  %h2= @checklist_template.title
  %h3= t('views.checklist_templates.show.tags') + @checklist_template.show_tags
  %ul
    - @template_items.each do |template_item|
      %li
        = template_item.title
        = delete_template_link(@checklist_template, template_item)

  = render 'new_template_item_modal', checklist_template: @checklist_template,
    template_item: @template_item if policy(@template_item).new?

  %p
    = link_to t('views.checklist_templates.create.checklist'),
      checklist_template_checklist_copy_path(@checklist_template), method: :post

  %p
    = link_to 'Show', checklist_template_show_index_path(@checklist_template)