config/routes.rb
Rails.application.routes.draw do
   devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :checklists do
    resources :show, only: [:index]

    resources :items, only: %i[new create update destroy] do
      resource :item_resolutions, only: [:create, :destroy]
    end
  end

  resources :checklist_templates do
    resources :show, only: [:index]
    resources :template_items, only: %i[create update destroy]
    resource :checklist_copy, only: %i[create]
  end

  resources :users do
    resources :checklist_templates, module: 'users', only: %i[index show]
  end

end

app/models/checklist.rb
# User's checklist based on checklist template
class Checklist < ApplicationRecord
  has_many :items, dependent: :destroy
  belongs_to :user
  belongs_to :checklist_template

  # find checklists that have not_done items and this checklists will be due next day
  # will not find checklist that have no items
  scope :due_date_tomorrow, lambda {
    joins(:items).where(items: { state: :not_done })
                 .where(due_date: Date.current.in_time_zone..Date.tomorrow.end_of_day.in_time_zone)
                 .distinct
  }

  validates :title, presence: true, length: { maximum: 100 }
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  before_action :checklist, only: %i[show update destroy]
  before_action only: %i[new] do
    authorize_role(:checklist)
  end

  def index
    @checklists = current_user.checklists.paginate(page: params[:page])
  end

  def show
  end

  def new
    @checklist_form = ChecklistForm.new
  end

  def create
    @checklist_form = ChecklistForm.new(checklist_form_params)
    authorize Checklist.new
    if @checklist_form.valid?
      service = ChecklistCreationService.new(checklist_form_params, current_user)
      service.run
      redirect_to checklist_path(service.checklist), notice: t('checklist.success_create')
    else
      redirect_to new_checklist_path, notice: t('checklist.fail_create')
    end
  end

  def update
    if @checklist.update(checklist_params)
      redirect_to checklist_path(@checklist), notice: t('checklist.success_update')
    else
      redirect_to checklist_path(@checklist), alert: t('checklist.fail_update')
    end
  end

  def destroy
    if @checklist.destroy
      redirect_to checklists_path, notice: t('checklist.success_destroy')
    else
      redirect_to checklist_path(@checklist), alert: t('checklist.fail_destroy')
    end
  end

  private

  def find_checklist_template
    @checklist_template = ChecklistTemplate.find(params[:checklist_template_id])
  end

  def checklist
    @checklist ||= Checklist.find(params[:id])
    authorize @checklist
  end

  def checklist_params
    params.require(:checklist).permit(:title, :due_date)
  end

  def checklist_form_params
    params.require(:checklist_form).permit(:title, :visibility)
  end
end

app/views/checklists/_checkbox_for_item.html.haml
- if item.not_done?
  = simple_form_for [checklist, item.becomes(Item)],
  url: checklist_item_item_resolutions_path(checklist, item), method: :post do |f|
    = f.check_box :state, checked: item.done?
- else
  = simple_form_for [checklist, item.becomes(Item)],
  url: checklist_item_item_resolutions_path(checklist, item), method: :delete do |f|
    = f.check_box :state, checked: item.done?

app/views/checklists/_checklist_edit_modal.html.haml
%a{ href: "#", "data-toggle" => "modal", "data-target" => "#checklist" }= t('edit_button')

.modal.fade{ id: "checklist", tabindex: "-1",
    role: "dialog", "aria-labelledby" => "exampleModalLabel", "aria-hidden" => "true" }
  .modal-dialog{ role: "document" }
    .modal-content
      .modal-header
        %h5.modal-title=  t('view.checklists.show.title')
        %button.close{ type: "button", "data-dismiss" => "modal", "aria-label" => "Close" }
          %span{ "aria-hidden" => "true" } &times;
      .modal-body
        = simple_form_for checklist do |f|
          = f.input :title
          = f.input :due_date, as: :string, input_html: { class: 'datepicker' }
          = f.button :submit
      .modal-footer
        %button.btn.btn-secondary{ type: "button", "data-dismiss" => "modal" }= t('button.close')

app/views/checklists/index.html.haml
.container
  %h1= t('views.checklists.index.title')
  %ul
    - @checklists.each do |checklist|
      %li= link_to checklist.title, checklist_path(checklist)

  = link_to t('views.checklists.create.title'), new_checklist_path
  = will_paginate @checklists

app/views/checklists/new.html.haml
.container
  = simple_form_for @checklist_form, url: checklists_path do |t|
    = t.input :title
    = t.input :visibility, collection: @checklist_form.states, include_blank: false, include_hidden: false
    = t.submit "Create checklist"

app/views/checklists/show.html.haml
.container
  %h1= t('views.checklists.show.title')
  %h2{ id: "checklist-field" }
    = @checklist.title
    = render "checklist_edit_modal", checklist: @checklist
    = link_to t('views.checklists.delete.title'),
      checklist_path(@checklist), method: :delete, data: { confirm: 'Are you sure?' }
  %ul
    - @checklist.items.each do |item|
      %li
        = render 'checkbox_for_item', item: item, checklist: @checklist
        = item.title
        = render "items/edit_item_modal", item: item, checklist: @checklist
        = link_to t('views.items.delete.title'),
          checklist_item_path(@checklist, item), method: :delete, data: { confirm: 'Are you sure?' }
  = link_to t('views.items.create.title'), new_checklist_item_path(@checklist)
  = link_to 'Show', checklist_show_index_path(@checklist)